### PR TITLE
Update js-ipfs-api, fixes #14

### LINKED ISSUE #14: Extension broken with 0.4.5-pre1
In 0.4.5, the format of the /api/v0/swarm/peers endpoint changes, so the extension shows that the daemon is offline regardless of its status.

### PR DESCRIPTION
**Pull request by mateon1**

### CODE REVIEW

**Comment by xicombd** [comment]
I've just uploaded [v0.1.0](https://github.com/xicombd/ipfs-chrome-station/releases/tag/v0.1.0) to the chrome web store, should become available in the next 60 mins

**Comment by mateon1** [comment]
This is unfortunate, I just checked the updated extension, and it seems that `ipfs-api` has a new dependency on `protocol-buffers`, which in turn depends on `generate-function`.
`generate-function` uses `Function("...")`, which triggers `unsafe-eval` in Chrome's extension CSP policy.

Oddly enough, this only triggers when using `npm run build`, but the extension works perfectly with `npm run dev`.

**Comment by lidel** [comment]
I think this was always the case for browser bundle of `ipfs-api`. 
I had to [whitelist `eval` in Firefox WebExtension too](https://github.com/lidel/ipfs-firefox-addon/blob/b2525ba2c6570a7893759a959763843da7316375/add-on/manifest.json#L76).

**Comment by xicombd** [comment]
Oops, only tested with `npm run dev`. The `dev` version [already had 'unsafe-eval'](https://github.com/xicombd/ipfs-chrome-station/blob/master/chrome/manifest.prod.json#L29) for the hot module loading if I'm not mistaken. 

I'll whitelist in the prod version too then :)

**Comment by AlexBeLi** [comment]
Very strange, not working for me. "Oh snap, it looks like your node is not running yet."
I use ipfs 0.4.7 from ipfs.io and Vivaldi
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.100 Safari/537.36 Vivaldi/1.8.770.32

**Comment by xicombd** [comment]
@AlexBeLi I've just installed Vivaldi and it seems to work for me with ipfs 0.4.7 😕 
Can you tell me what's the version you've got installed? Is it 0.1.1? You can check it at vivaldi://extensions

**Comment by AlexBeLi** [comment]
IPFS Station 0.1.1
Maybe something with my ipfs settings? 
```
\.ipfs\config
 "Bootstrap": [
    ...
  ],
  "Datastore": {
    "BloomFilterSize": 0,
    "GCPeriod": "1h",
    "HashOnRead": false,
    "NoSync": false,
    "Params": null,
    "Path": "C:\\path-to-my-folder\\.ipfs\\datastore",
    "StorageGCWatermark": 90,
    "StorageMax": "10GB",
    "Type": "leveldb"
  },
  "Discovery": {
    "MDNS": {
      "Enabled": false,
      "Interval": 10
    }
  },
  "Gateway": {
    "HTTPHeaders": null,
    "PathPrefixes": null,
    "RootRedirect": "",
    "Writable": false
  },
  "Identity": {
   ...
  },
  "Ipns": {
    "RecordLifetime": "",
    "RepublishPeriod": "",
    "ResolveCacheSize": 128
  },
  "Mounts": {
    "FuseAllowOther": false,
    "IPFS": "/ipfs",
    "IPNS": "/ipns"
  },
  "SupernodeRouting": {
    "Servers": [
   ...
    ]
  },
  "Swarm": {
    "AddrFilters": null
  },
  "Tour": {
    "Last": ""
  },
  "Version": {
    "AutoUpdate": "minor",
    "Check": "error",
    "CheckDate": "0001-01-01T00:00:00Z",
    "CheckPeriod": "172800000000000",
    "Current": "0.3.11"
  }
}
```
in addon
```
ipfs node details
localhost
8080
5001
5000
```

**Comment by xicombd** [comment]
Try setting the CORS headers: `ipfs config API.HTTPHeaders '{"Access-Control-Allow-Origin": ["*"]}' --json`

**Comment by AlexBeLi** [comment]
```
>ipfs config API.HTTPHeaders '{"Access-Control-Allow-Origin": ["*"]}' --json
Error: Unknown Command "API.HTTPHeaders"
```

**Comment by xicombd** [comment]
Maybe try with the `--json` beforehand? `ipfs config --json API.HTTPHeaders '{"Access-Control-Allow-Origin": ["*"]}'`

Super weird, both ways work for me:  
screen shot 2017-03-19 at 19 35 12

If if still doesn't work you can also try changing the config on the webui: http://127.0.0.1:5001/ipfs/QmPhnvn747LqwPYMJmQVorMaGbMSgA7mRRoyyZYz3DoZRQ/#/config

**Comment by AlexBeLi** [comment]
Thanks, It's work fine:)

**Comment by whyrusleeping** [comment]
@mateon1 @lidel if we get this issue fixed: https://github.com/mafintosh/protocol-buffers/issues/18
we should be able to avoid the eval stuff, should make for a slightly nicer experience no?

**Comment by lidel** [comment]
@whyrusleeping Removal of `eval` would speed up future reviews at Mozilla, for sure.
Right now we need special CSP exception (`unsafe-eval`) in [add-on/manifest.json#L79](https://github.com/lidel/ipfs-firefox-addon/blob/0e6418b8161b0813e801aa459e508bd7ee20e479/add-on/manifest.json#L79), which triggers additional review at [AMO](https://addons.mozilla.org):

```
WARNINGS:

Code           Message                                       Description                                                 File   Line   Column
MANIFEST_CSP   "content_security_policy" is defined in the   A custom content_security_policy needs additional review.                       
               manifest.json
```

**Pull request merged**
